version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/webapp/
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu